"""Agent state schemas and Gemini structured output contracts.

Implements TRD.md §M, PLAN.md T-SCHEMA-04, and Phase 6 structured output contracts.
Explicitly distinguishes LLM-generated outputs from deterministic fallback via provenance metadata.
"""

from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4
from pydantic import BaseModel, Field

from risk_manager.domain.schemas.enums import (
    Action,
    AgentFallbackReason,
    AgentName,
    AgentProvider,
    AgentRunStatus,
    EvidenceQuality,
    VerifierRecommendation,
)


class InvestigationResult(BaseModel):
    """Structured output contract for Investigator agent (TRD.md §M & Phase 6)."""

    case_id: UUID = Field(default_factory=uuid4, description="Correlation / risk decision ID")
    agent_name: AgentName = Field(default=AgentName.INVESTIGATOR)
    status: AgentRunStatus = Field(default=AgentRunStatus.COMPLETED)

    # Provenance tracking (Issue 2)
    provider: str = Field(
        default=AgentProvider.DETERMINISTIC_FALLBACK.value,
        description="GEMINI or DETERMINISTIC_FALLBACK",
    )
    is_llm_generated: bool = Field(
        default=False,
        description="True if generated by real Gemini LLM, False if deterministic fallback",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Explicit reason when fallback occurs, None when Gemini succeeds",
    )
    model_name: str | None = Field(
        default=None,
        description="Model name/version if generated by Gemini LLM",
    )

    # Phase 6 rich structured fields
    evidence_summary: str = Field(
        default="", description="Executive synthesis of behavioral and transactional facts"
    )
    key_risk_factors: list[str] = Field(
        default_factory=list, description="Dominant signals indicating return abuse or risk"
    )
    mitigating_factors: list[str] = Field(
        default_factory=list, description="Protective signals indicating legitimate customer behavior"
    )
    evidence_quality: EvidenceQuality = Field(
        default=EvidenceQuality.MEDIUM, description="Assessment of evidence completeness and strength"
    )
    missing_information: list[str] = Field(
        default_factory=list, description="Missing features, history, or telemetry"
    )
    contradictions: list[str] = Field(
        default_factory=list, description="Contradictions within customer data or order facts"
    )
    confidence: float = Field(default=0.85, ge=0.0, le=1.0, description="Agent confidence score")
    recommendation: str = Field(
        default="PROCEED", description="Investigator operational recommendation (PROCEED/ESCALATE)"
    )
    prompt_injection_detected: bool = Field(
        default=False, description="Flag indicating adversarial prompt injection attempt detected"
    )
    source_decision_id: UUID | None = Field(
        default=None, description="Reference to original immutable risk decision"
    )

    # Backward compatibility with Phase 2 TRD.md §M
    evidence: list[str] = Field(
        default_factory=list, description="Synthesized behavioral facts list"
    )
    anomalies: list[str] = Field(
        default_factory=list, description="Unusual transactional or timing patterns"
    )
    investigator_confidence: float = Field(
        default=0.85, ge=0.0, le=1.0, description="Confidence alias for backward compatibility"
    )


class VerificationResult(BaseModel):
    """Structured output contract for Verifier agent (TRD.md §M & Phase 6)."""

    case_id: UUID = Field(default_factory=uuid4, description="Correlation / risk decision ID")
    agent_name: AgentName = Field(default=AgentName.VERIFIER)
    status: AgentRunStatus = Field(default=AgentRunStatus.COMPLETED)

    # Provenance tracking (Issue 2)
    provider: str = Field(
        default=AgentProvider.DETERMINISTIC_FALLBACK.value,
        description="GEMINI or DETERMINISTIC_FALLBACK",
    )
    is_llm_generated: bool = Field(
        default=False,
        description="True if generated by real Gemini LLM, False if deterministic fallback",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Explicit reason when fallback occurs, None when Gemini succeeds",
    )
    model_name: str | None = Field(
        default=None,
        description="Model name/version if generated by Gemini LLM",
    )

    # Phase 6 rich verification fields
    verification_status: str = Field(
        default="VERIFIED", description="VERIFIED, FAILED, DISAGREEMENT, or INCONCLUSIVE"
    )
    checks: list[str] = Field(
        default_factory=list, description="List of consistency checks evaluated"
    )
    failed_checks: list[str] = Field(
        default_factory=list, description="Any checks that failed during consistency verification"
    )
    warnings: list[str] = Field(
        default_factory=list, description="Non-fatal anomalies or advisory warnings"
    )
    disagreements: list[str] = Field(
        default_factory=list, description="Explicit disagreements with numerical or investigator outputs"
    )
    recommendation: VerifierRecommendation = Field(
        default=VerifierRecommendation.CONFIRM, description="CONFIRM or MANUAL_REVIEW"
    )
    requires_human_review: bool = Field(
        default=False, description="True if any critical inconsistency requires human review"
    )
    confidence: float = Field(
        default=0.90, ge=0.0, le=1.0, description="Verifier confidence in assessment"
    )

    # Backward compatibility with Phase 2 TRD.md §M
    verified: bool = Field(
        default=True, description="False if contradictions found between model and facts"
    )
    contradictions: list[str] = Field(
        default_factory=list, description="Contradictory signals detected"
    )
    missing_evidence: list[str] = Field(
        default_factory=list, description="Unresolvable missing data"
    )
    verifier_confidence: float = Field(
        default=0.90, ge=0.0, le=1.0, description="Confidence alias for backward compatibility"
    )


class ActionDecision(BaseModel):
    """Structured output contract for Action Orchestrator agent (TRD.md §M & Phase 6)."""

    agent_name: AgentName = Field(default=AgentName.ACTION_ORCHESTRATOR)
    status: AgentRunStatus = Field(default=AgentRunStatus.COMPLETED)

    # Provenance tracking (Issue 2)
    provider: str = Field(
        default=AgentProvider.DETERMINISTIC_FALLBACK.value,
        description="GEMINI or DETERMINISTIC_FALLBACK",
    )
    is_llm_generated: bool = Field(
        default=False,
        description="True if generated by real Gemini LLM, False if deterministic fallback",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Explicit reason when fallback occurs, None when Gemini succeeds",
    )
    model_name: str | None = Field(
        default=None,
        description="Model name/version if generated by Gemini LLM",
    )

    # Phase 6 operational recommendation fields
    selected_action_reference: Action = Field(
        default=Action.A0, description="Immutable reference to the Phase 5 selected action"
    )
    execution_mode: str = Field(
        default="AUTOMATED",
        description="AUTOMATED (direct pipeline), MANUAL_REVIEW_QUEUE (route to human), ESCALATED",
    )
    operational_recommendation: str = Field(
        default="CONFIRM", description="Operational execution guidance for fulfillment"
    )
    requires_human_review: bool = Field(
        default=False, description="True if operational review required before intervention"
    )
    blockers: list[str] = Field(
        default_factory=list, description="Operational blockers preventing immediate execution"
    )
    confidence: float = Field(
        default=0.95, ge=0.0, le=1.0, description="Orchestrator confidence"
    )

    # Backward compatibility with Phase 2 TRD.md §M
    action: Action = Field(
        default=Action.A0, description="Selected action alias"
    )
    rationale: str = Field(
        default="", description="Operational rationale explanation"
    )
    expected_net_value: float = Field(
        default=0.0, description="Preserved economic expected net value"
    )
    policy_constraints_satisfied: bool = Field(
        default=True, description="Whether guardrails were validated"
    )
    requires_manual_review: bool = Field(
        default=False, description="Alias for requires_human_review"
    )


class AgentVerificationResult(BaseModel):
    """Legacy alias matching TRD.md §E DTO contract."""

    case_id: UUID
    verified: bool
    contradictions: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    verifier_confidence: float = Field(ge=0, le=1)
    recommendation: VerifierRecommendation


class AgentWorkflowResult(BaseModel):
    """Final aggregated result of the asynchronous LangGraph multi-agent workflow."""

    decision_id: UUID
    risk_decision_id: UUID
    policy_decision_id: UUID
    p_return_abuse: float = Field(ge=0.0, le=1.0, description="Immutable numerical score from Phase 4")
    risk_band: str
    selected_action: Action = Field(description="Immutable selected action from Phase 5")
    expected_loss: float = Field(default=0.0, description="Authoritative expected loss from Phase 5")
    expected_net_value: float = Field(default=0.0, description="Authoritative expected net value from Phase 5")

    # Provenance tracking (Issue 2)
    provider: str = Field(
        default=AgentProvider.DETERMINISTIC_FALLBACK.value,
        description="GEMINI or DETERMINISTIC_FALLBACK",
    )
    is_llm_generated: bool = Field(
        default=False,
        description="True if generated by real Gemini LLM, False if deterministic fallback",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Explicit reason when fallback occurs, None when Gemini succeeds",
    )
    model_name: str | None = Field(
        default=None,
        description="Configured or used model name",
    )

    investigator_result: InvestigationResult | None = None
    verifier_result: VerificationResult | None = None
    orchestrator_result: ActionDecision | None = None
    requires_human_review: bool = False
    disagreements: list[str] = Field(default_factory=list)
    final_agent_recommendation: str = "CONFIRM"
    agent_status: AgentRunStatus = AgentRunStatus.COMPLETED
    agent_errors: list[str] = Field(default_factory=list)
    latency_ms: float = 0.0
    trace_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
