"""Observability, Prometheus metrics, and distributed tracing package (Phase 8)."""

from risk_manager.observability.metrics import (
    HTTP_ERRORS_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
    RISK_DECISIONS_TOTAL,
    RISK_DECISION_DURATION_SECONDS,
    RISK_FALLBACK_TOTAL,
    RISK_BAND_TOTAL,
    POLICY_DECISIONS_TOTAL,
    POLICY_DECISION_DURATION_SECONDS,
    INTERVENTION_ACTION_TOTAL,
    AGENT_WORKFLOW_TOTAL,
    AGENT_WORKFLOW_DURATION_SECONDS,
    AGENT_FAILURES_TOTAL,
    AGENT_FALLBACK_TOTAL,
    AGENT_HUMAN_REVIEW_TOTAL,
    HUMAN_REVIEW_REQUIRED_TOTAL,
    HUMAN_OVERRIDE_TOTAL,
    PERSISTENCE_OPERATION_TOTAL,
    PERSISTENCE_FAILURE_TOTAL,
    PROMPT_INJECTION_DETECTED_TOTAL,
    get_metrics_payload,
)
from risk_manager.observability.middleware import ObservabilityMiddleware
from risk_manager.observability.scrubber import (
    is_sensitive_key,
    sanitize_text,
    scrub_data,
    scrub_trace_attributes,
)
from risk_manager.observability.tracer import (
    get_current_span_id,
    get_current_trace_id,
    get_tracer,
    init_tracer,
    trace_span,
    traced,
)

__all__ = [
    "init_tracer",
    "get_tracer",
    "trace_span",
    "traced",
    "get_current_trace_id",
    "get_current_span_id",
    "scrub_data",
    "scrub_trace_attributes",
    "sanitize_text",
    "is_sensitive_key",
    "ObservabilityMiddleware",
    "get_metrics_payload",
    "HTTP_REQUESTS_TOTAL",
    "HTTP_REQUEST_DURATION_SECONDS",
    "HTTP_ERRORS_TOTAL",
    "RISK_DECISIONS_TOTAL",
    "RISK_DECISION_DURATION_SECONDS",
    "RISK_FALLBACK_TOTAL",
    "RISK_BAND_TOTAL",
    "POLICY_DECISIONS_TOTAL",
    "POLICY_DECISION_DURATION_SECONDS",
    "INTERVENTION_ACTION_TOTAL",
    "AGENT_WORKFLOW_TOTAL",
    "AGENT_WORKFLOW_DURATION_SECONDS",
    "AGENT_FAILURES_TOTAL",
    "AGENT_FALLBACK_TOTAL",
    "AGENT_HUMAN_REVIEW_TOTAL",
    "HUMAN_REVIEW_REQUIRED_TOTAL",
    "HUMAN_OVERRIDE_TOTAL",
    "PERSISTENCE_OPERATION_TOTAL",
    "PERSISTENCE_FAILURE_TOTAL",
    "PROMPT_INJECTION_DETECTED_TOTAL",
]
